//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Win.Repository
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    using Service.Win.Common.Model;
    using Service.Windows.Repository;

    public partial class YMEntities : DbContext
    {
        public YMEntities()
            : base("name=YMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Database-First model - no additional configuration needed
        }
    
        public virtual DbSet<tbl_MessageCommunication> tbl_MessageCommunication { get; set; }
        public virtual DbSet<tbl_MessageTemplate> tbl_MessageTemplate { get; set; }
        public virtual DbSet<tbl_CSATransaction> tbl_CSATransaction { get; set; }
        public virtual DbSet<tbl_MessageQueue> tbl_MessageQueue { get; set; }
        public virtual DbSet<tbl_MessageQueueAttachment> tbl_MessageQueueAttachment { get; set; }
        public virtual DbSet<tbl_ReportMaster> tbl_ReportMaster { get; set; }
        public virtual DbSet<tbl_ScheduleReport> tbl_ScheduleReport { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }

        public virtual int pro_GetDateTime(string type, string fromDate, string toDate, Nullable<int> venueBranchNo, ObjectParameter fDate, ObjectParameter tDate)
        {
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_GetDateTime", typeParameter, fromDateParameter, toDateParameter, venueBranchNoParameter, fDate, tDate);
        }    
        public virtual ObjectResult<Pro_GetMessageList_Result> Pro_GetMessageList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_GetMessageList_Result>("Pro_GetMessageList");
        }    
        [DbFunction("YMEntities", "Split_Custom")]
        public virtual IQueryable<Split_Custom_Result> Split_Custom(string dELIMITER, string lIST)
        {
            var dELIMITERParameter = dELIMITER != null ?
                new ObjectParameter("DELIMITER", dELIMITER) :
                new ObjectParameter("DELIMITER", typeof(string));
    
            var lISTParameter = lIST != null ?
                new ObjectParameter("LIST", lIST) :
                new ObjectParameter("LIST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Custom_Result>("[YMEntities].[Split_Custom](@DELIMITER, @LIST)", dELIMITERParameter, lISTParameter);
        }    
        public virtual ObjectResult<Pro_CsaAppTransaction_Result> Pro_CsaAppTransaction(Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> param, Nullable<int> userNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var paramParameter = param.HasValue ?
                new ObjectParameter("Param", param) :
                new ObjectParameter("Param", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_CsaAppTransaction_Result>("Pro_CsaAppTransaction", venueNoParameter, venueBranchNoParameter, paramParameter, userNoParameter);
        }    
        public virtual ObjectResult<Pro_GetCustomerDetails_Result> Pro_GetCustomerDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_GetCustomerDetails_Result>("Pro_GetCustomerDetails");
        }    
        public virtual ObjectResult<Nullable<decimal>> pro_InsertCsaTransaction(Nullable<int> customerNo, Nullable<int> sampleCount, Nullable<decimal> collectedAmount, Nullable<int> userNo, Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var customerNoParameter = customerNo.HasValue ?
                new ObjectParameter("CustomerNo", customerNo) :
                new ObjectParameter("CustomerNo", typeof(int));
    
            var sampleCountParameter = sampleCount.HasValue ?
                new ObjectParameter("SampleCount", sampleCount) :
                new ObjectParameter("SampleCount", typeof(int));
    
            var collectedAmountParameter = collectedAmount.HasValue ?
                new ObjectParameter("CollectedAmount", collectedAmount) :
                new ObjectParameter("CollectedAmount", typeof(decimal));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("userNo", userNo) :
                new ObjectParameter("userNo", typeof(int));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pro_InsertCsaTransaction", customerNoParameter, sampleCountParameter, collectedAmountParameter, userNoParameter, venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<Pro_LoadCustomer_Result> Pro_LoadCustomer(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_LoadCustomer_Result>("Pro_LoadCustomer", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual int Pro_PushMessage(string templateKey, string messageType, string address, string cCAddress, string bCCAddress, string messageXML, Nullable<bool> isAttachment, string messageAttachmentXML, Nullable<System.DateTime> scheduleTime, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo, Nullable<int> patientVisitNo, Nullable<int> customerNo)
        {
            var templateKeyParameter = templateKey != null ?
                new ObjectParameter("TemplateKey", templateKey) :
                new ObjectParameter("TemplateKey", typeof(string));
    
            var messageTypeParameter = messageType != null ?
                new ObjectParameter("MessageType", messageType) :
                new ObjectParameter("MessageType", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var cCAddressParameter = cCAddress != null ?
                new ObjectParameter("CCAddress", cCAddress) :
                new ObjectParameter("CCAddress", typeof(string));
    
            var bCCAddressParameter = bCCAddress != null ?
                new ObjectParameter("BCCAddress", bCCAddress) :
                new ObjectParameter("BCCAddress", typeof(string));
    
            var messageXMLParameter = messageXML != null ?
                new ObjectParameter("MessageXML", messageXML) :
                new ObjectParameter("MessageXML", typeof(string));
    
            var isAttachmentParameter = isAttachment.HasValue ?
                new ObjectParameter("IsAttachment", isAttachment) :
                new ObjectParameter("IsAttachment", typeof(bool));
    
            var messageAttachmentXMLParameter = messageAttachmentXML != null ?
                new ObjectParameter("MessageAttachmentXML", messageAttachmentXML) :
                new ObjectParameter("MessageAttachmentXML", typeof(string));
    
            var scheduleTimeParameter = scheduleTime.HasValue ?
                new ObjectParameter("ScheduleTime", scheduleTime) :
                new ObjectParameter("ScheduleTime", typeof(System.DateTime));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            var patientVisitNoParameter = patientVisitNo.HasValue ?
                new ObjectParameter("PatientVisitNo", patientVisitNo) :
                new ObjectParameter("PatientVisitNo", typeof(int));
    
            var customerNoParameter = customerNo.HasValue ?
                new ObjectParameter("CustomerNo", customerNo) :
                new ObjectParameter("CustomerNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pro_PushMessage", templateKeyParameter, messageTypeParameter, addressParameter, cCAddressParameter, bCCAddressParameter, messageXMLParameter, isAttachmentParameter, messageAttachmentXMLParameter, scheduleTimeParameter, venueNoParameter, venueBranchNoParameter, userNoParameter, patientVisitNoParameter, customerNoParameter);
        }    
        public virtual ObjectResult<Pro_DrpCustomer_Result> Pro_DrpCustomer(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_DrpCustomer_Result>("Pro_DrpCustomer", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> pro_InsertExternalOrders(string patientID, string patientName, string barcodeno, string sex, string dOB, string parameterCode, string parameter)
        {
            var patientIDParameter = patientID != null ?
                new ObjectParameter("PatientID", patientID) :
                new ObjectParameter("PatientID", typeof(string));
    
            var patientNameParameter = patientName != null ?
                new ObjectParameter("PatientName", patientName) :
                new ObjectParameter("PatientName", typeof(string));
    
            var barcodenoParameter = barcodeno != null ?
                new ObjectParameter("Barcodeno", barcodeno) :
                new ObjectParameter("Barcodeno", typeof(string));
    
            var sexParameter = sex != null ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(string));
    
            var dOBParameter = dOB != null ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(string));
    
            var parameterCodeParameter = parameterCode != null ?
                new ObjectParameter("ParameterCode", parameterCode) :
                new ObjectParameter("ParameterCode", typeof(string));
    
            var parameterParameter = parameter != null ?
                new ObjectParameter("parameter", parameter) :
                new ObjectParameter("parameter", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pro_InsertExternalOrders", patientIDParameter, patientNameParameter, barcodenoParameter, sexParameter, dOBParameter, parameterCodeParameter, parameterParameter);
        }    
        public virtual int pro_updateICMRResult(Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> iCMRResultNo, string statusresponse, string iCMRID)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var iCMRResultNoParameter = iCMRResultNo.HasValue ?
                new ObjectParameter("ICMRResultNo", iCMRResultNo) :
                new ObjectParameter("ICMRResultNo", typeof(int));
    
            var statusresponseParameter = statusresponse != null ?
                new ObjectParameter("Statusresponse", statusresponse) :
                new ObjectParameter("Statusresponse", typeof(string));
    
            var iCMRIDParameter = iCMRID != null ?
                new ObjectParameter("ICMRID", iCMRID) :
                new ObjectParameter("ICMRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_updateICMRResult", venueNoParameter, venueBranchNoParameter, iCMRResultNoParameter, statusresponseParameter, iCMRIDParameter);
        }    
        public virtual ObjectResult<pro_GetICMRResultDetails_Result> pro_GetICMRResultDetails(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetICMRResultDetails_Result>("pro_GetICMRResultDetails", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<pro_GetICMRResultDetails1_Result> pro_GetICMRResultDetails1(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetICMRResultDetails1_Result>("pro_GetICMRResultDetails1", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<pro_GetICMRResultDetails_v1_Result> pro_GetICMRResultDetails_v1(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetICMRResultDetails_v1_Result>("pro_GetICMRResultDetails_v1", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual int pro_updateICMRResult_v1(Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> iCMRResultNo, string statusresponse, string iCMRID)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var iCMRResultNoParameter = iCMRResultNo.HasValue ?
                new ObjectParameter("ICMRResultNo", iCMRResultNo) :
                new ObjectParameter("ICMRResultNo", typeof(int));
    
            var statusresponseParameter = statusresponse != null ?
                new ObjectParameter("Statusresponse", statusresponse) :
                new ObjectParameter("Statusresponse", typeof(string));
    
            var iCMRIDParameter = iCMRID != null ?
                new ObjectParameter("ICMRID", iCMRID) :
                new ObjectParameter("ICMRID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_updateICMRResult_v1", venueNoParameter, venueBranchNoParameter, iCMRResultNoParameter, statusresponseParameter, iCMRIDParameter);
        }    
        public virtual ObjectResult<Nullable<int>> Pro_MasterRecord(string departmentXML, string methodNameXML, string sampleNameXML, string containerNameXML, string unitNameXML, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo)
        {
            var departmentXMLParameter = departmentXML != null ?
                new ObjectParameter("DepartmentXML", departmentXML) :
                new ObjectParameter("DepartmentXML", typeof(string));
    
            var methodNameXMLParameter = methodNameXML != null ?
                new ObjectParameter("MethodNameXML", methodNameXML) :
                new ObjectParameter("MethodNameXML", typeof(string));
    
            var sampleNameXMLParameter = sampleNameXML != null ?
                new ObjectParameter("SampleNameXML", sampleNameXML) :
                new ObjectParameter("SampleNameXML", typeof(string));
    
            var containerNameXMLParameter = containerNameXML != null ?
                new ObjectParameter("ContainerNameXML", containerNameXML) :
                new ObjectParameter("ContainerNameXML", typeof(string));
    
            var unitNameXMLParameter = unitNameXML != null ?
                new ObjectParameter("UnitNameXML", unitNameXML) :
                new ObjectParameter("UnitNameXML", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pro_MasterRecord", departmentXMLParameter, methodNameXMLParameter, sampleNameXMLParameter, containerNameXMLParameter, unitNameXMLParameter, venueNoParameter, venueBranchNoParameter, userNoParameter);
        }    
        public virtual ObjectResult<pro_CommonDetails_Result> pro_CommonDetails(string masterKey, Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var masterKeyParameter = masterKey != null ?
                new ObjectParameter("MasterKey", masterKey) :
                new ObjectParameter("MasterKey", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_CommonDetails_Result>("pro_CommonDetails", masterKeyParameter, venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> Pro_MasterTestRecord(string testXML, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo)
        {
            var testXMLParameter = testXML != null ?
                new ObjectParameter("TestXML", testXML) :
                new ObjectParameter("TestXML", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pro_MasterTestRecord", testXMLParameter, venueNoParameter, venueBranchNoParameter, userNoParameter);
        }    
        public virtual ObjectResult<pro_GetICMRResultDetails_v2_Result> pro_GetICMRResultDetails_v2(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetICMRResultDetails_v2_Result>("pro_GetICMRResultDetails_v2", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> Pro_MasterRecord1(string departmentXML, string methodNameXML, string sampleNameXML, string containerNameXML, string unitNameXML, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo)
        {
            var departmentXMLParameter = departmentXML != null ?
                new ObjectParameter("DepartmentXML", departmentXML) :
                new ObjectParameter("DepartmentXML", typeof(string));
    
            var methodNameXMLParameter = methodNameXML != null ?
                new ObjectParameter("MethodNameXML", methodNameXML) :
                new ObjectParameter("MethodNameXML", typeof(string));
    
            var sampleNameXMLParameter = sampleNameXML != null ?
                new ObjectParameter("SampleNameXML", sampleNameXML) :
                new ObjectParameter("SampleNameXML", typeof(string));
    
            var containerNameXMLParameter = containerNameXML != null ?
                new ObjectParameter("ContainerNameXML", containerNameXML) :
                new ObjectParameter("ContainerNameXML", typeof(string));
    
            var unitNameXMLParameter = unitNameXML != null ?
                new ObjectParameter("UnitNameXML", unitNameXML) :
                new ObjectParameter("UnitNameXML", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pro_MasterRecord1", departmentXMLParameter, methodNameXMLParameter, sampleNameXMLParameter, containerNameXMLParameter, unitNameXMLParameter, venueNoParameter, venueBranchNoParameter, userNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> Pro_MasterTestRecord1(string testXML, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo)
        {
            var testXMLParameter = testXML != null ?
                new ObjectParameter("TestXML", testXML) :
                new ObjectParameter("TestXML", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pro_MasterTestRecord1", testXMLParameter, venueNoParameter, venueBranchNoParameter, userNoParameter);
        }    
        public virtual ObjectResult<Pro_SchedulePatientReport_Result> Pro_SchedulePatientReport(Nullable<System.DateTime> fROMDate, Nullable<System.DateTime> toDate, Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var fROMDateParameter = fROMDate.HasValue ?
                new ObjectParameter("FROMDate", fROMDate) :
                new ObjectParameter("FROMDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_SchedulePatientReport_Result>("Pro_SchedulePatientReport", fROMDateParameter, toDateParameter, venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<pro_CommonDetails_V1_Result> pro_CommonDetails_V1(string masterKey, Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var masterKeyParameter = masterKey != null ?
                new ObjectParameter("MasterKey", masterKey) :
                new ObjectParameter("MasterKey", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_CommonDetails_V1_Result>("pro_CommonDetails_V1", masterKeyParameter, venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> Pro_MasterRecord_V2(string departmentXML, string methodNameXML, string sampleNameXML, string containerNameXML, string unitNameXML, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo)
        {
            var departmentXMLParameter = departmentXML != null ?
                new ObjectParameter("DepartmentXML", departmentXML) :
                new ObjectParameter("DepartmentXML", typeof(string));
    
            var methodNameXMLParameter = methodNameXML != null ?
                new ObjectParameter("MethodNameXML", methodNameXML) :
                new ObjectParameter("MethodNameXML", typeof(string));
    
            var sampleNameXMLParameter = sampleNameXML != null ?
                new ObjectParameter("SampleNameXML", sampleNameXML) :
                new ObjectParameter("SampleNameXML", typeof(string));
    
            var containerNameXMLParameter = containerNameXML != null ?
                new ObjectParameter("ContainerNameXML", containerNameXML) :
                new ObjectParameter("ContainerNameXML", typeof(string));
    
            var unitNameXMLParameter = unitNameXML != null ?
                new ObjectParameter("UnitNameXML", unitNameXML) :
                new ObjectParameter("UnitNameXML", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pro_MasterRecord_V2", departmentXMLParameter, methodNameXMLParameter, sampleNameXMLParameter, containerNameXMLParameter, unitNameXMLParameter, venueNoParameter, venueBranchNoParameter, userNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> Pro_MasterTestRecord_V1(string testXML, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo)
        {
            var testXMLParameter = testXML != null ?
                new ObjectParameter("TestXML", testXML) :
                new ObjectParameter("TestXML", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pro_MasterTestRecord_V1", testXMLParameter, venueNoParameter, venueBranchNoParameter, userNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> Pro_InsertTestReferenceRange(string testRefXML, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo)
        {
            var testRefXMLParameter = testRefXML != null ?
                new ObjectParameter("TestRefXML", testRefXML) :
                new ObjectParameter("TestRefXML", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("UserNo", userNo) :
                new ObjectParameter("UserNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Pro_InsertTestReferenceRange", testRefXMLParameter, venueNoParameter, venueBranchNoParameter, userNoParameter);
        }    
        public virtual ObjectResult<string> Pro_InsertQueueOrder(string title, string patientName, string gender, Nullable<System.DateTime> dOB, Nullable<int> age, string ageType, string mobileNo, string email, Nullable<int> uIDType, string uIDNo, string localbodiestype, string localbodies, string serviceNos, string serviceNames, string serviceTypes, string address, string area, string pincode, Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var titleParameter = title != null ?
                new ObjectParameter("Title", title) :
                new ObjectParameter("Title", typeof(string));
    
            var patientNameParameter = patientName != null ?
                new ObjectParameter("PatientName", patientName) :
                new ObjectParameter("PatientName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var ageTypeParameter = ageType != null ?
                new ObjectParameter("AgeType", ageType) :
                new ObjectParameter("AgeType", typeof(string));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("MobileNo", mobileNo) :
                new ObjectParameter("MobileNo", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var uIDTypeParameter = uIDType.HasValue ?
                new ObjectParameter("UIDType", uIDType) :
                new ObjectParameter("UIDType", typeof(int));
    
            var uIDNoParameter = uIDNo != null ?
                new ObjectParameter("UIDNo", uIDNo) :
                new ObjectParameter("UIDNo", typeof(string));
    
            var localbodiestypeParameter = localbodiestype != null ?
                new ObjectParameter("localbodiestype", localbodiestype) :
                new ObjectParameter("localbodiestype", typeof(string));
    
            var localbodiesParameter = localbodies != null ?
                new ObjectParameter("localbodies", localbodies) :
                new ObjectParameter("localbodies", typeof(string));
    
            var serviceNosParameter = serviceNos != null ?
                new ObjectParameter("ServiceNos", serviceNos) :
                new ObjectParameter("ServiceNos", typeof(string));
    
            var serviceNamesParameter = serviceNames != null ?
                new ObjectParameter("ServiceNames", serviceNames) :
                new ObjectParameter("ServiceNames", typeof(string));
    
            var serviceTypesParameter = serviceTypes != null ?
                new ObjectParameter("ServiceTypes", serviceTypes) :
                new ObjectParameter("ServiceTypes", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var areaParameter = area != null ?
                new ObjectParameter("Area", area) :
                new ObjectParameter("Area", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("Pincode", pincode) :
                new ObjectParameter("Pincode", typeof(string));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Pro_InsertQueueOrder", titleParameter, patientNameParameter, genderParameter, dOBParameter, ageParameter, ageTypeParameter, mobileNoParameter, emailParameter, uIDTypeParameter, uIDNoParameter, localbodiestypeParameter, localbodiesParameter, serviceNosParameter, serviceNamesParameter, serviceTypesParameter, addressParameter, areaParameter, pincodeParameter, venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<Pro_GetCustomerNotification_Result> Pro_GetCustomerNotification(Nullable<int> patientVisitNo, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> type)
        {
            var patientVisitNoParameter = patientVisitNo.HasValue ?
                new ObjectParameter("PatientVisitNo", patientVisitNo) :
                new ObjectParameter("PatientVisitNo", typeof(int));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_GetCustomerNotification_Result>("Pro_GetCustomerNotification", patientVisitNoParameter, venueNoParameter, venueBranchNoParameter, typeParameter);
        }    
        public virtual ObjectResult<pro_GetAutoApprovalResults_Result> pro_GetAutoApprovalResults()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetAutoApprovalResults_Result>("pro_GetAutoApprovalResults");
        }    
        public virtual int pro_UpdateAutoApprovalResults(Nullable<int> patientVisitNo, Nullable<int> venueno, Nullable<int> venuebranchno)
        {
            var patientVisitNoParameter = patientVisitNo.HasValue ?
                new ObjectParameter("PatientVisitNo", patientVisitNo) :
                new ObjectParameter("PatientVisitNo", typeof(int));
    
            var venuenoParameter = venueno.HasValue ?
                new ObjectParameter("venueno", venueno) :
                new ObjectParameter("venueno", typeof(int));
    
            var venuebranchnoParameter = venuebranchno.HasValue ?
                new ObjectParameter("venuebranchno", venuebranchno) :
                new ObjectParameter("venuebranchno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pro_UpdateAutoApprovalResults", patientVisitNoParameter, venuenoParameter, venuebranchnoParameter);
        }    
        public virtual ObjectResult<pro_GetMessageCommunication_Result> pro_GetMessageCommunication(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetMessageCommunication_Result>("pro_GetMessageCommunication", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<Nullable<int>> pro_InsertMessageCommunication(string host, string username, string password, Nullable<int> port, Nullable<bool> isSSL, string param1, string param2, string param3, string communicationType, Nullable<int> venueno, Nullable<int> venueBranchNo, Nullable<int> userno, string templatecode, string subject, string body, string messagetype, Nullable<int> communicationno, Nullable<int> messageTemplateNo, string ccaddress, string bccaddress, Nullable<bool> templateStatus)
        {
            var hostParameter = host != null ?
                new ObjectParameter("Host", host) :
                new ObjectParameter("Host", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var portParameter = port.HasValue ?
                new ObjectParameter("Port", port) :
                new ObjectParameter("Port", typeof(int));
    
            var isSSLParameter = isSSL.HasValue ?
                new ObjectParameter("IsSSL", isSSL) :
                new ObjectParameter("IsSSL", typeof(bool));
    
            var param1Parameter = param1 != null ?
                new ObjectParameter("Param1", param1) :
                new ObjectParameter("Param1", typeof(string));
    
            var param2Parameter = param2 != null ?
                new ObjectParameter("Param2", param2) :
                new ObjectParameter("Param2", typeof(string));
    
            var param3Parameter = param3 != null ?
                new ObjectParameter("Param3", param3) :
                new ObjectParameter("Param3", typeof(string));
    
            var communicationTypeParameter = communicationType != null ?
                new ObjectParameter("CommunicationType", communicationType) :
                new ObjectParameter("CommunicationType", typeof(string));
    
            var venuenoParameter = venueno.HasValue ?
                new ObjectParameter("Venueno", venueno) :
                new ObjectParameter("Venueno", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var usernoParameter = userno.HasValue ?
                new ObjectParameter("Userno", userno) :
                new ObjectParameter("Userno", typeof(int));
    
            var templatecodeParameter = templatecode != null ?
                new ObjectParameter("Templatecode", templatecode) :
                new ObjectParameter("Templatecode", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("Subject", subject) :
                new ObjectParameter("Subject", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("Body", body) :
                new ObjectParameter("Body", typeof(string));
    
            var messagetypeParameter = messagetype != null ?
                new ObjectParameter("Messagetype", messagetype) :
                new ObjectParameter("Messagetype", typeof(string));
    
            var communicationnoParameter = communicationno.HasValue ?
                new ObjectParameter("Communicationno", communicationno) :
                new ObjectParameter("Communicationno", typeof(int));
    
            var messageTemplateNoParameter = messageTemplateNo.HasValue ?
                new ObjectParameter("MessageTemplateNo", messageTemplateNo) :
                new ObjectParameter("MessageTemplateNo", typeof(int));
    
            var ccaddressParameter = ccaddress != null ?
                new ObjectParameter("Ccaddress", ccaddress) :
                new ObjectParameter("Ccaddress", typeof(string));
    
            var bccaddressParameter = bccaddress != null ?
                new ObjectParameter("Bccaddress", bccaddress) :
                new ObjectParameter("Bccaddress", typeof(string));
    
            var templateStatusParameter = templateStatus.HasValue ?
                new ObjectParameter("TemplateStatus", templateStatus) :
                new ObjectParameter("TemplateStatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("pro_InsertMessageCommunication", hostParameter, usernameParameter, passwordParameter, portParameter, isSSLParameter, param1Parameter, param2Parameter, param3Parameter, communicationTypeParameter, venuenoParameter, venueBranchNoParameter, usernoParameter, templatecodeParameter, subjectParameter, bodyParameter, messagetypeParameter, communicationnoParameter, messageTemplateNoParameter, ccaddressParameter, bccaddressParameter, templateStatusParameter);
        }    
        public virtual ObjectResult<pro_GetMessageCommunications_Result> pro_GetMessageCommunications(Nullable<int> venueNo, Nullable<int> venueBranchNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetMessageCommunications_Result>("pro_GetMessageCommunications", venueNoParameter, venueBranchNoParameter);
        }    
        public virtual ObjectResult<pro_GetMessageCommunicationlst_Result> pro_GetMessageCommunicationlst(Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> communicationNo, Nullable<int> mesgTemplateNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var communicationNoParameter = communicationNo.HasValue ?
                new ObjectParameter("CommunicationNo", communicationNo) :
                new ObjectParameter("CommunicationNo", typeof(int));
    
            var mesgTemplateNoParameter = mesgTemplateNo.HasValue ?
                new ObjectParameter("MesgTemplateNo", mesgTemplateNo) :
                new ObjectParameter("MesgTemplateNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetMessageCommunicationlst_Result>("pro_GetMessageCommunicationlst", venueNoParameter, venueBranchNoParameter, communicationNoParameter, mesgTemplateNoParameter);
        }    
        public virtual ObjectResult<pro_GetMessageCommunicationgrid_Result> pro_GetMessageCommunicationgrid(Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> communicationNo, Nullable<int> mesgTemplateNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var communicationNoParameter = communicationNo.HasValue ?
                new ObjectParameter("CommunicationNo", communicationNo) :
                new ObjectParameter("CommunicationNo", typeof(int));
    
            var mesgTemplateNoParameter = mesgTemplateNo.HasValue ?
                new ObjectParameter("MesgTemplateNo", mesgTemplateNo) :
                new ObjectParameter("MesgTemplateNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetMessageCommunicationgrid_Result>("pro_GetMessageCommunicationgrid", venueNoParameter, venueBranchNoParameter, communicationNoParameter, mesgTemplateNoParameter);
        }    
        public virtual ObjectResult<pro_GetMessageCommunicationList_Result> pro_GetMessageCommunicationList(Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> communicationNo, Nullable<int> mesgTemplateNo)
        {
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var communicationNoParameter = communicationNo.HasValue ?
                new ObjectParameter("CommunicationNo", communicationNo) :
                new ObjectParameter("CommunicationNo", typeof(int));
    
            var mesgTemplateNoParameter = mesgTemplateNo.HasValue ?
                new ObjectParameter("MesgTemplateNo", mesgTemplateNo) :
                new ObjectParameter("MesgTemplateNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetMessageCommunicationList_Result>("pro_GetMessageCommunicationList", venueNoParameter, venueBranchNoParameter, communicationNoParameter, mesgTemplateNoParameter);
        }    
        public virtual IEnumerable<Pro_GetMessageQueueList_Result> Pro_GetMessageQueueList_Email()
        {
            return this.Database.SqlQuery<Pro_GetMessageQueueList_Result>("EXEC Pro_GetMessageQueueList_Email");
        }    
        public virtual IEnumerable<Pro_GetMessageQueueList_Result> Pro_GetMessageQueueList_WMS()
        {
            return this.Database.SqlQuery<Pro_GetMessageQueueList_Result>("EXEC Pro_GetMessageQueueList_WMS");
        }    
        public virtual ObjectResult<pro_GetOPDPhysicianAppointment_Result> pro_GetOPDPhysicianAppointment(string appointmentDate, Nullable<int> physicianNo, Nullable<int> specializationNo, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> physicianVenueBranchNo)
        {
            var appointmentDateParameter = appointmentDate != null ?
                new ObjectParameter("AppointmentDate", appointmentDate) :
                new ObjectParameter("AppointmentDate", typeof(string));
    
            var physicianNoParameter = physicianNo.HasValue ?
                new ObjectParameter("PhysicianNo", physicianNo) :
                new ObjectParameter("PhysicianNo", typeof(int));
    
            var specializationNoParameter = specializationNo.HasValue ?
                new ObjectParameter("SpecializationNo", specializationNo) :
                new ObjectParameter("SpecializationNo", typeof(int));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var physicianVenueBranchNoParameter = physicianVenueBranchNo.HasValue ?
                new ObjectParameter("PhysicianVenueBranchNo", physicianVenueBranchNo) :
                new ObjectParameter("PhysicianVenueBranchNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetOPDPhysicianAppointment_Result>("pro_GetOPDPhysicianAppointment", appointmentDateParameter, physicianNoParameter, specializationNoParameter, venueNoParameter, venueBranchNoParameter, physicianVenueBranchNoParameter);
        }    
        public virtual ObjectResult<pro_GetOPDBookingdata_Result> pro_GetOPDBookingdata(string appointmentDate, Nullable<int> physicianNo, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> physicianVenueBranchNo, Nullable<int> bookingType)
        {
            var appointmentDateParameter = appointmentDate != null ?
                new ObjectParameter("AppointmentDate", appointmentDate) :
                new ObjectParameter("AppointmentDate", typeof(string));
    
            var physicianNoParameter = physicianNo.HasValue ?
                new ObjectParameter("PhysicianNo", physicianNo) :
                new ObjectParameter("PhysicianNo", typeof(int));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var physicianVenueBranchNoParameter = physicianVenueBranchNo.HasValue ?
                new ObjectParameter("PhysicianVenueBranchNo", physicianVenueBranchNo) :
                new ObjectParameter("PhysicianVenueBranchNo", typeof(int));
    
            var bookingTypeParameter = bookingType.HasValue ?
                new ObjectParameter("BookingType", bookingType) :
                new ObjectParameter("BookingType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetOPDBookingdata_Result>("pro_GetOPDBookingdata", appointmentDateParameter, physicianNoParameter, venueNoParameter, venueBranchNoParameter, physicianVenueBranchNoParameter, bookingTypeParameter);
        }    
        public virtual ObjectResult<pro_InsertOPDPatient_Result> pro_InsertOPDPatient(Nullable<int> oPDPatientNo, Nullable<int> oPDPatientAppointmentNo, string titleCode, string firstName, string middleName, string lastName, Nullable<System.DateTime> dOB, string gender, Nullable<int> age, string ageType, string mobileNumber, string whatsappNo, string emailID, string secondaryEmailID, string address, Nullable<int> countryNo, Nullable<int> stateNo, Nullable<int> cityNo, string areaName, string pincode, Nullable<int> appointmentMode, Nullable<int> specializationNo, Nullable<int> physicianNo, string reason, Nullable<System.DateTime> appointmentDateTime, Nullable<System.DateTime> arrivedDateTime, Nullable<int> appointmentStatus, Nullable<bool> isNew, Nullable<bool> isEmergency, Nullable<bool> isVIP, Nullable<int> venueNo, Nullable<int> venueBranchNo, Nullable<int> userNo, string emiratesId, Nullable<bool> isAutoEmail, Nullable<bool> isAutoSMS, Nullable<bool> isAutoWhatsApp, Nullable<bool> isSysCalDOB, Nullable<int> patientVisitID, Nullable<int> reasonType, Nullable<int> refferalType, Nullable<int> physNo, string refTypeothers, Nullable<System.DateTime> lastVisitDate, Nullable<decimal> lastConfees, string prevApptProcedureDtlXML)
        {
            var oPDPatientNoParameter = oPDPatientNo.HasValue ?
                new ObjectParameter("OPDPatientNo", oPDPatientNo) :
                new ObjectParameter("OPDPatientNo", typeof(int));
    
            var oPDPatientAppointmentNoParameter = oPDPatientAppointmentNo.HasValue ?
                new ObjectParameter("oPDPatientAppointmentNo", oPDPatientAppointmentNo) :
                new ObjectParameter("oPDPatientAppointmentNo", typeof(int));
    
            var titleCodeParameter = titleCode != null ?
                new ObjectParameter("TitleCode", titleCode) :
                new ObjectParameter("TitleCode", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var middleNameParameter = middleName != null ?
                new ObjectParameter("MiddleName", middleName) :
                new ObjectParameter("MiddleName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var dOBParameter = dOB.HasValue ?
                new ObjectParameter("DOB", dOB) :
                new ObjectParameter("DOB", typeof(System.DateTime));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("Age", age) :
                new ObjectParameter("Age", typeof(int));
    
            var ageTypeParameter = ageType != null ?
                new ObjectParameter("AgeType", ageType) :
                new ObjectParameter("AgeType", typeof(string));
    
            var mobileNumberParameter = mobileNumber != null ?
                new ObjectParameter("MobileNumber", mobileNumber) :
                new ObjectParameter("MobileNumber", typeof(string));
    
            var whatsappNoParameter = whatsappNo != null ?
                new ObjectParameter("WhatsappNo", whatsappNo) :
                new ObjectParameter("WhatsappNo", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var secondaryEmailIDParameter = secondaryEmailID != null ?
                new ObjectParameter("SecondaryEmailID", secondaryEmailID) :
                new ObjectParameter("SecondaryEmailID", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var countryNoParameter = countryNo.HasValue ?
                new ObjectParameter("CountryNo", countryNo) :
                new ObjectParameter("CountryNo", typeof(int));
    
            var stateNoParameter = stateNo.HasValue ?
                new ObjectParameter("StateNo", stateNo) :
                new ObjectParameter("StateNo", typeof(int));
    
            var cityNoParameter = cityNo.HasValue ?
                new ObjectParameter("CityNo", cityNo) :
                new ObjectParameter("CityNo", typeof(int));
    
            var areaNameParameter = areaName != null ?
                new ObjectParameter("AreaName", areaName) :
                new ObjectParameter("AreaName", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("Pincode", pincode) :
                new ObjectParameter("Pincode", typeof(string));
    
            var appointmentModeParameter = appointmentMode.HasValue ?
                new ObjectParameter("AppointmentMode", appointmentMode) :
                new ObjectParameter("AppointmentMode", typeof(int));
    
            var specializationNoParameter = specializationNo.HasValue ?
                new ObjectParameter("SpecializationNo", specializationNo) :
                new ObjectParameter("SpecializationNo", typeof(int));
    
            var physicianNoParameter = physicianNo.HasValue ?
                new ObjectParameter("PhysicianNo", physicianNo) :
                new ObjectParameter("PhysicianNo", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            var appointmentDateTimeParameter = appointmentDateTime.HasValue ?
                new ObjectParameter("AppointmentDateTime", appointmentDateTime) :
                new ObjectParameter("AppointmentDateTime", typeof(System.DateTime));
    
            var arrivedDateTimeParameter = arrivedDateTime.HasValue ?
                new ObjectParameter("ArrivedDateTime", arrivedDateTime) :
                new ObjectParameter("ArrivedDateTime", typeof(System.DateTime));
    
            var appointmentStatusParameter = appointmentStatus.HasValue ?
                new ObjectParameter("appointmentStatus", appointmentStatus) :
                new ObjectParameter("appointmentStatus", typeof(int));
    
            var isNewParameter = isNew.HasValue ?
                new ObjectParameter("IsNew", isNew) :
                new ObjectParameter("IsNew", typeof(bool));
    
            var isEmergencyParameter = isEmergency.HasValue ?
                new ObjectParameter("IsEmergency", isEmergency) :
                new ObjectParameter("IsEmergency", typeof(bool));
    
            var isVIPParameter = isVIP.HasValue ?
                new ObjectParameter("IsVIP", isVIP) :
                new ObjectParameter("IsVIP", typeof(bool));
    
            var venueNoParameter = venueNo.HasValue ?
                new ObjectParameter("VenueNo", venueNo) :
                new ObjectParameter("VenueNo", typeof(int));
    
            var venueBranchNoParameter = venueBranchNo.HasValue ?
                new ObjectParameter("VenueBranchNo", venueBranchNo) :
                new ObjectParameter("VenueBranchNo", typeof(int));
    
            var userNoParameter = userNo.HasValue ?
                new ObjectParameter("userNo", userNo) :
                new ObjectParameter("userNo", typeof(int));
    
            var emiratesIdParameter = emiratesId != null ?
                new ObjectParameter("EmiratesId", emiratesId) :
                new ObjectParameter("EmiratesId", typeof(string));
    
            var isAutoEmailParameter = isAutoEmail.HasValue ?
                new ObjectParameter("IsAutoEmail", isAutoEmail) :
                new ObjectParameter("IsAutoEmail", typeof(bool));
    
            var isAutoSMSParameter = isAutoSMS.HasValue ?
                new ObjectParameter("IsAutoSMS", isAutoSMS) :
                new ObjectParameter("IsAutoSMS", typeof(bool));
    
            var isAutoWhatsAppParameter = isAutoWhatsApp.HasValue ?
                new ObjectParameter("IsAutoWhatsApp", isAutoWhatsApp) :
                new ObjectParameter("IsAutoWhatsApp", typeof(bool));
    
            var isSysCalDOBParameter = isSysCalDOB.HasValue ?
                new ObjectParameter("IsSysCalDOB", isSysCalDOB) :
                new ObjectParameter("IsSysCalDOB", typeof(bool));
    
            var patientVisitIDParameter = patientVisitID.HasValue ?
                new ObjectParameter("PatientVisitID", patientVisitID) :
                new ObjectParameter("PatientVisitID", typeof(int));
    
            var reasonTypeParameter = reasonType.HasValue ?
                new ObjectParameter("ReasonType", reasonType) :
                new ObjectParameter("ReasonType", typeof(int));
    
            var refferalTypeParameter = refferalType.HasValue ?
                new ObjectParameter("RefferalType", refferalType) :
                new ObjectParameter("RefferalType", typeof(int));
    
            var physNoParameter = physNo.HasValue ?
                new ObjectParameter("PhysNo", physNo) :
                new ObjectParameter("PhysNo", typeof(int));
    
            var refTypeothersParameter = refTypeothers != null ?
                new ObjectParameter("RefTypeothers", refTypeothers) :
                new ObjectParameter("RefTypeothers", typeof(string));
    
            var lastVisitDateParameter = lastVisitDate.HasValue ?
                new ObjectParameter("LastVisitDate", lastVisitDate) :
                new ObjectParameter("LastVisitDate", typeof(System.DateTime));
    
            var lastConfeesParameter = lastConfees.HasValue ?
                new ObjectParameter("LastConfees", lastConfees) :
                new ObjectParameter("LastConfees", typeof(decimal));
    
            var prevApptProcedureDtlXMLParameter = prevApptProcedureDtlXML != null ?
                new ObjectParameter("prevApptProcedureDtlXML", prevApptProcedureDtlXML) :
                new ObjectParameter("prevApptProcedureDtlXML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_InsertOPDPatient_Result>("pro_InsertOPDPatient", oPDPatientNoParameter, oPDPatientAppointmentNoParameter, titleCodeParameter, firstNameParameter, middleNameParameter, lastNameParameter, dOBParameter, genderParameter, ageParameter, ageTypeParameter, mobileNumberParameter, whatsappNoParameter, emailIDParameter, secondaryEmailIDParameter, addressParameter, countryNoParameter, stateNoParameter, cityNoParameter, areaNameParameter, pincodeParameter, appointmentModeParameter, specializationNoParameter, physicianNoParameter, reasonParameter, appointmentDateTimeParameter, arrivedDateTimeParameter, appointmentStatusParameter, isNewParameter, isEmergencyParameter, isVIPParameter, venueNoParameter, venueBranchNoParameter, userNoParameter, emiratesIdParameter, isAutoEmailParameter, isAutoSMSParameter, isAutoWhatsAppParameter, isSysCalDOBParameter, patientVisitIDParameter, reasonTypeParameter, refferalTypeParameter, physNoParameter, refTypeothersParameter, lastVisitDateParameter, lastConfeesParameter, prevApptProcedureDtlXMLParameter);
        }    
        public virtual ObjectResult<pro_GetScheduledPatientreport_Result> pro_GetScheduledPatientreport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pro_GetScheduledPatientreport_Result>("pro_GetScheduledPatientreport");
        }
        public virtual ObjectResult<ReportDownloadListDTO> pro_get_scheduled_patientreport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportDownloadListDTO>("pro_get_scheduled_patientreport");
        }
    }
}
