//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCMS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientLiteParameterDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class PatientLiteParameterDTO : object
    {
        
        private RCMS.PatientLiteSearchParameter SearchParameterField;
        
        private string SystemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientLiteSearchParameter SearchParameter
        {
            get
            {
                return this.SearchParameterField;
            }
            set
            {
                this.SearchParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemId
        {
            get
            {
                return this.SystemIdField;
            }
            set
            {
                this.SystemIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientLiteSearchParameter", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class PatientLiteSearchParameter : object
    {
        
        private string IdNumberField;
        
        private bool IncludeInactiveRecordField;
        
        private string NameField;
        
        private int[] PatientSystemIdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber
        {
            get
            {
                return this.IdNumberField;
            }
            set
            {
                this.IdNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeInactiveRecord
        {
            get
            {
                return this.IncludeInactiveRecordField;
            }
            set
            {
                this.IncludeInactiveRecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] PatientSystemIds
        {
            get
            {
                return this.PatientSystemIdsField;
            }
            set
            {
                this.PatientSystemIdsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientLiteReturnDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class PatientLiteReturnDTO : object
    {
        
        private RCMS.ReturnDTO ReturnStatusField;
        
        private RCMS.PatientLiteSearchResult[] SearchResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.ReturnDTO ReturnStatus
        {
            get
            {
                return this.ReturnStatusField;
            }
            set
            {
                this.ReturnStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientLiteSearchResult[] SearchResult
        {
            get
            {
                return this.SearchResultField;
            }
            set
            {
                this.SearchResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class ReturnDTO : object
    {
        
        private string MessageField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientLiteSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class PatientLiteSearchResult : object
    {
        
        private System.DateTime DateOfBirthField;
        
        private string EMRVIPDesignationField;
        
        private bool EMRVIPStatusField;
        
        private string GenderField;
        
        private bool HasECCHistoryField;
        
        private string IDNumberField;
        
        private string IDTypeField;
        
        private bool IsAllergyField;
        
        private bool IsRCMSMedicalAlertField;
        
        private string NameField;
        
        private string NameAliasField;
        
        private string PatientActiveSystemIdField;
        
        private string PatientSystemIdField;
        
        private string RCMSVIPDesignationField;
        
        private bool RCMSVIPStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMRVIPDesignation
        {
            get
            {
                return this.EMRVIPDesignationField;
            }
            set
            {
                this.EMRVIPDesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EMRVIPStatus
        {
            get
            {
                return this.EMRVIPStatusField;
            }
            set
            {
                this.EMRVIPStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasECCHistory
        {
            get
            {
                return this.HasECCHistoryField;
            }
            set
            {
                this.HasECCHistoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber
        {
            get
            {
                return this.IDNumberField;
            }
            set
            {
                this.IDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDType
        {
            get
            {
                return this.IDTypeField;
            }
            set
            {
                this.IDTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllergy
        {
            get
            {
                return this.IsAllergyField;
            }
            set
            {
                this.IsAllergyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRCMSMedicalAlert
        {
            get
            {
                return this.IsRCMSMedicalAlertField;
            }
            set
            {
                this.IsRCMSMedicalAlertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAlias
        {
            get
            {
                return this.NameAliasField;
            }
            set
            {
                this.NameAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientActiveSystemId
        {
            get
            {
                return this.PatientActiveSystemIdField;
            }
            set
            {
                this.PatientActiveSystemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientSystemId
        {
            get
            {
                return this.PatientSystemIdField;
            }
            set
            {
                this.PatientSystemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RCMSVIPDesignation
        {
            get
            {
                return this.RCMSVIPDesignationField;
            }
            set
            {
                this.RCMSVIPDesignationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RCMSVIPStatus
        {
            get
            {
                return this.RCMSVIPStatusField;
            }
            set
            {
                this.RCMSVIPStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientInfoParameterDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class PatientInfoParameterDTO : object
    {
        
        private RCMS.PatientInfoSearchParameter SearchParameterField;
        
        private string SystemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientInfoSearchParameter SearchParameter
        {
            get
            {
                return this.SearchParameterField;
            }
            set
            {
                this.SearchParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemId
        {
            get
            {
                return this.SystemIdField;
            }
            set
            {
                this.SystemIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientInfoSearchParameter", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class PatientInfoSearchParameter : object
    {
        
        private bool IncludeInactiveRecordField;
        
        private string[] PatientSystemIdsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeInactiveRecord
        {
            get
            {
                return this.IncludeInactiveRecordField;
            }
            set
            {
                this.IncludeInactiveRecordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PatientSystemIds
        {
            get
            {
                return this.PatientSystemIdsField;
            }
            set
            {
                this.PatientSystemIdsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientInfoReturnDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class PatientInfoReturnDTO : object
    {
        
        private RCMS.ReturnDTO ReturnStatusField;
        
        private RCMS.PatientInfoSearchResult[] SearchResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.ReturnDTO ReturnStatus
        {
            get
            {
                return this.ReturnStatusField;
            }
            set
            {
                this.ReturnStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientInfoSearchResult[] SearchResult
        {
            get
            {
                return this.SearchResultField;
            }
            set
            {
                this.SearchResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientInfoSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class PatientInfoSearchResult : object
    {
        
        private string AlterNativeIDTypeField;
        
        private string AlternativeIDNumberField;
        
        private string BloodGroupField;
        
        private string CountryOfResidenceField;
        
        private System.DateTime DateOfBirthField;
        
        private string EmailField;
        
        private RCMS.ForeignAddressSearchResult ForeignAddressField;
        
        private string GenderField;
        
        private string HomeNoField;
        
        private string IDNumberField;
        
        private string IDTypeField;
        
        private bool IsAllergyField;
        
        private string LastVisitClinicCodeField;
        
        private string LastVisitClinicNameField;
        
        private System.Nullable<System.DateTime> LastVisitDateField;
        
        private RCMS.LocalAddressSearchResult LocalAddressField;
        
        private string MaritalStatusField;
        
        private RCMS.MedicalAlertSearchResult[] MedicalAlertField;
        
        private string MobileField;
        
        private string NameField;
        
        private string NameAliasField;
        
        private string NationalityField;
        
        private string NationalityCodeField;
        
        private string OccupationField;
        
        private string OfficeNoField;
        
        private string PatientAlertField;
        
        private RCMS.AllergySearchResult[] PatientAllergyField;
        
        private string PatientRemarksField;
        
        private string PatientSystemIdField;
        
        private RCMS.PrivateMedicalInsuranceSearchResult[] PrivateMedicalInsuranceField;
        
        private string RaceField;
        
        private RCMS.RafflesProgrammeSearchResult[] RafflesJuniorProgrammeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlterNativeIDType
        {
            get
            {
                return this.AlterNativeIDTypeField;
            }
            set
            {
                this.AlterNativeIDTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativeIDNumber
        {
            get
            {
                return this.AlternativeIDNumberField;
            }
            set
            {
                this.AlternativeIDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BloodGroup
        {
            get
            {
                return this.BloodGroupField;
            }
            set
            {
                this.BloodGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryOfResidence
        {
            get
            {
                return this.CountryOfResidenceField;
            }
            set
            {
                this.CountryOfResidenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.ForeignAddressSearchResult ForeignAddress
        {
            get
            {
                return this.ForeignAddressField;
            }
            set
            {
                this.ForeignAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeNo
        {
            get
            {
                return this.HomeNoField;
            }
            set
            {
                this.HomeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber
        {
            get
            {
                return this.IDNumberField;
            }
            set
            {
                this.IDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDType
        {
            get
            {
                return this.IDTypeField;
            }
            set
            {
                this.IDTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAllergy
        {
            get
            {
                return this.IsAllergyField;
            }
            set
            {
                this.IsAllergyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastVisitClinicCode
        {
            get
            {
                return this.LastVisitClinicCodeField;
            }
            set
            {
                this.LastVisitClinicCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastVisitClinicName
        {
            get
            {
                return this.LastVisitClinicNameField;
            }
            set
            {
                this.LastVisitClinicNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastVisitDate
        {
            get
            {
                return this.LastVisitDateField;
            }
            set
            {
                this.LastVisitDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.LocalAddressSearchResult LocalAddress
        {
            get
            {
                return this.LocalAddressField;
            }
            set
            {
                this.LocalAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaritalStatus
        {
            get
            {
                return this.MaritalStatusField;
            }
            set
            {
                this.MaritalStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.MedicalAlertSearchResult[] MedicalAlert
        {
            get
            {
                return this.MedicalAlertField;
            }
            set
            {
                this.MedicalAlertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameAlias
        {
            get
            {
                return this.NameAliasField;
            }
            set
            {
                this.NameAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalityCode
        {
            get
            {
                return this.NationalityCodeField;
            }
            set
            {
                this.NationalityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Occupation
        {
            get
            {
                return this.OccupationField;
            }
            set
            {
                this.OccupationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeNo
        {
            get
            {
                return this.OfficeNoField;
            }
            set
            {
                this.OfficeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientAlert
        {
            get
            {
                return this.PatientAlertField;
            }
            set
            {
                this.PatientAlertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.AllergySearchResult[] PatientAllergy
        {
            get
            {
                return this.PatientAllergyField;
            }
            set
            {
                this.PatientAllergyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientRemarks
        {
            get
            {
                return this.PatientRemarksField;
            }
            set
            {
                this.PatientRemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientSystemId
        {
            get
            {
                return this.PatientSystemIdField;
            }
            set
            {
                this.PatientSystemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PrivateMedicalInsuranceSearchResult[] PrivateMedicalInsurance
        {
            get
            {
                return this.PrivateMedicalInsuranceField;
            }
            set
            {
                this.PrivateMedicalInsuranceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Race
        {
            get
            {
                return this.RaceField;
            }
            set
            {
                this.RaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.RafflesProgrammeSearchResult[] RafflesJuniorProgramme
        {
            get
            {
                return this.RafflesJuniorProgrammeField;
            }
            set
            {
                this.RafflesJuniorProgrammeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAddressSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class ForeignAddressSearchResult : object
    {
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string AddressLine3Field;
        
        private string CountryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1
        {
            get
            {
                return this.AddressLine1Field;
            }
            set
            {
                this.AddressLine1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2
        {
            get
            {
                return this.AddressLine2Field;
            }
            set
            {
                this.AddressLine2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3
        {
            get
            {
                return this.AddressLine3Field;
            }
            set
            {
                this.AddressLine3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalAddressSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class LocalAddressSearchResult : object
    {
        
        private string BlockHouseLotNumberField;
        
        private string BuildingField;
        
        private string CountryField;
        
        private string FloorNoField;
        
        private string PostalCodeField;
        
        private string StreetField;
        
        private string UnitNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlockHouseLotNumber
        {
            get
            {
                return this.BlockHouseLotNumberField;
            }
            set
            {
                this.BlockHouseLotNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Building
        {
            get
            {
                return this.BuildingField;
            }
            set
            {
                this.BuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorNo
        {
            get
            {
                return this.FloorNoField;
            }
            set
            {
                this.FloorNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitNo
        {
            get
            {
                return this.UnitNoField;
            }
            set
            {
                this.UnitNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicalAlertSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class MedicalAlertSearchResult : object
    {
        
        private string MedicalAlertField;
        
        private string MedicalAlertLastUpdatedByField;
        
        private System.DateTime MedicalAlertLastUpdatedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalAlert
        {
            get
            {
                return this.MedicalAlertField;
            }
            set
            {
                this.MedicalAlertField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalAlertLastUpdatedBy
        {
            get
            {
                return this.MedicalAlertLastUpdatedByField;
            }
            set
            {
                this.MedicalAlertLastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MedicalAlertLastUpdatedDate
        {
            get
            {
                return this.MedicalAlertLastUpdatedDateField;
            }
            set
            {
                this.MedicalAlertLastUpdatedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllergySearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class AllergySearchResult : object
    {
        
        private string AllergyInfoField;
        
        private string AllergyLastUpdatedByField;
        
        private System.DateTime AllergyLastUpdatedDateField;
        
        private string AllergyRemarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllergyInfo
        {
            get
            {
                return this.AllergyInfoField;
            }
            set
            {
                this.AllergyInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllergyLastUpdatedBy
        {
            get
            {
                return this.AllergyLastUpdatedByField;
            }
            set
            {
                this.AllergyLastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AllergyLastUpdatedDate
        {
            get
            {
                return this.AllergyLastUpdatedDateField;
            }
            set
            {
                this.AllergyLastUpdatedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AllergyRemark
        {
            get
            {
                return this.AllergyRemarkField;
            }
            set
            {
                this.AllergyRemarkField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrivateMedicalInsuranceSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce.SearchResult")]
    public partial class PrivateMedicalInsuranceSearchResult : object
    {
        
        private string PMIIndicatorField;
        
        private string PMIInsuranceField;
        
        private string PMIRemarkField;
        
        private string PMIRemarkLastUpdatedByField;
        
        private System.DateTime PMIRemarkLastUpdatedDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PMIIndicator
        {
            get
            {
                return this.PMIIndicatorField;
            }
            set
            {
                this.PMIIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PMIInsurance
        {
            get
            {
                return this.PMIInsuranceField;
            }
            set
            {
                this.PMIInsuranceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PMIRemark
        {
            get
            {
                return this.PMIRemarkField;
            }
            set
            {
                this.PMIRemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PMIRemarkLastUpdatedBy
        {
            get
            {
                return this.PMIRemarkLastUpdatedByField;
            }
            set
            {
                this.PMIRemarkLastUpdatedByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PMIRemarkLastUpdatedDate
        {
            get
            {
                return this.PMIRemarkLastUpdatedDateField;
            }
            set
            {
                this.PMIRemarkLastUpdatedDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RafflesProgrammeSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce.SearchResult")]
    public partial class RafflesProgrammeSearchResult : object
    {
        
        private string ContractCodeField;
        
        private System.Nullable<System.DateTime> StartOnField;
        
        private System.Nullable<System.DateTime> TerminateOnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractCode
        {
            get
            {
                return this.ContractCodeField;
            }
            set
            {
                this.ContractCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartOn
        {
            get
            {
                return this.StartOnField;
            }
            set
            {
                this.StartOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TerminateOn
        {
            get
            {
                return this.TerminateOnField;
            }
            set
            {
                this.TerminateOnField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientQueueParameterDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class PatientQueueParameterDTO : object
    {
        
        private RCMS.PatientQueueSearchParameter SearchParameterField;
        
        private string SystemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientQueueSearchParameter SearchParameter
        {
            get
            {
                return this.SearchParameterField;
            }
            set
            {
                this.SearchParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemId
        {
            get
            {
                return this.SystemIdField;
            }
            set
            {
                this.SystemIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientQueueSearchParameter", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class PatientQueueSearchParameter : object
    {
        
        private string ClinicCodeField;
        
        private string DoctorMCRField;
        
        private System.DateTime EndDateField;
        
        private string EntityCodeField;
        
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClinicCode
        {
            get
            {
                return this.ClinicCodeField;
            }
            set
            {
                this.ClinicCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorMCR
        {
            get
            {
                return this.DoctorMCRField;
            }
            set
            {
                this.DoctorMCRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityCode
        {
            get
            {
                return this.EntityCodeField;
            }
            set
            {
                this.EntityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientQueueReturnDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class PatientQueueReturnDTO : object
    {
        
        private string ClinicCodeField;
        
        private string ClinicNameField;
        
        private string EntityCodeField;
        
        private RCMS.ReturnDTO ReturnStatusField;
        
        private RCMS.PatientQueueSearchResult[] SearchResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClinicCode
        {
            get
            {
                return this.ClinicCodeField;
            }
            set
            {
                this.ClinicCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClinicName
        {
            get
            {
                return this.ClinicNameField;
            }
            set
            {
                this.ClinicNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityCode
        {
            get
            {
                return this.EntityCodeField;
            }
            set
            {
                this.EntityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.ReturnDTO ReturnStatus
        {
            get
            {
                return this.ReturnStatusField;
            }
            set
            {
                this.ReturnStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientQueueSearchResult[] SearchResult
        {
            get
            {
                return this.SearchResultField;
            }
            set
            {
                this.SearchResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientQueueSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class PatientQueueSearchResult : object
    {
        
        private RCMS.AppointmentSearchResult AppointmentSearchResultField;
        
        private long QueueIdField;
        
        private string QueueNumberField;
        
        private short QueueStatusIdField;
        
        private string QueueSystemCodeField;
        
        private RCMS.VisitLiteSearchResult VisitLiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.AppointmentSearchResult AppointmentSearchResult
        {
            get
            {
                return this.AppointmentSearchResultField;
            }
            set
            {
                this.AppointmentSearchResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long QueueId
        {
            get
            {
                return this.QueueIdField;
            }
            set
            {
                this.QueueIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueueNumber
        {
            get
            {
                return this.QueueNumberField;
            }
            set
            {
                this.QueueNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short QueueStatusId
        {
            get
            {
                return this.QueueStatusIdField;
            }
            set
            {
                this.QueueStatusIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueueSystemCode
        {
            get
            {
                return this.QueueSystemCodeField;
            }
            set
            {
                this.QueueSystemCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.VisitLiteSearchResult VisitLite
        {
            get
            {
                return this.VisitLiteField;
            }
            set
            {
                this.VisitLiteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class AppointmentSearchResult : object
    {
        
        private System.DateTime AppointmentDateTimeField;
        
        private string AppointmentIdField;
        
        private string ClinicCodeField;
        
        private RCMS.DoctorSearchResult DoctorSearchResultField;
        
        private string EntityCodeField;
        
        private RCMS.PatientLiteSearchResult PatientLiteSearchResultField;
        
        private string RemarksField;
        
        private string SpecialtyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AppointmentDateTime
        {
            get
            {
                return this.AppointmentDateTimeField;
            }
            set
            {
                this.AppointmentDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppointmentId
        {
            get
            {
                return this.AppointmentIdField;
            }
            set
            {
                this.AppointmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClinicCode
        {
            get
            {
                return this.ClinicCodeField;
            }
            set
            {
                this.ClinicCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.DoctorSearchResult DoctorSearchResult
        {
            get
            {
                return this.DoctorSearchResultField;
            }
            set
            {
                this.DoctorSearchResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityCode
        {
            get
            {
                return this.EntityCodeField;
            }
            set
            {
                this.EntityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientLiteSearchResult PatientLiteSearchResult
        {
            get
            {
                return this.PatientLiteSearchResultField;
            }
            set
            {
                this.PatientLiteSearchResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remarks
        {
            get
            {
                return this.RemarksField;
            }
            set
            {
                this.RemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specialty
        {
            get
            {
                return this.SpecialtyField;
            }
            set
            {
                this.SpecialtyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisitLiteSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class VisitLiteSearchResult : object
    {
        
        private string AppointmentIdField;
        
        private System.Nullable<System.DateTime> BillingDateTimeField;
        
        private RCMS.ClinicLiteSearchResult ClinicLiteSearchResultField;
        
        private RCMS.DoctorSearchResult DoctorSearchResultField;
        
        private string ECCVisitModeField;
        
        private string EMRReferralInField;
        
        private string EntityCodeField;
        
        private bool FallRiskField;
        
        private string HealthPlanCodeField;
        
        private bool LabOrderedField;
        
        private bool MedOrderedField;
        
        private bool NoConsultationField;
        
        private RCMS.PatientLiteSearchResult PatientLiteSearchResultField;
        
        private bool ProcedureOrderedField;
        
        private bool RadOrderedField;
        
        private System.DateTime RegistrationDateTimeField;
        
        private string ServiceTypeCodeField;
        
        private string ServiceTypeDescriptionField;
        
        private bool VaccineInjectionOrderedField;
        
        private string VisitActiveStatusField;
        
        private string VisitNumberField;
        
        private string VisitRemarksField;
        
        private string VisitTypeCodeField;
        
        private string VisitTypeDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppointmentId
        {
            get
            {
                return this.AppointmentIdField;
            }
            set
            {
                this.AppointmentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BillingDateTime
        {
            get
            {
                return this.BillingDateTimeField;
            }
            set
            {
                this.BillingDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.ClinicLiteSearchResult ClinicLiteSearchResult
        {
            get
            {
                return this.ClinicLiteSearchResultField;
            }
            set
            {
                this.ClinicLiteSearchResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.DoctorSearchResult DoctorSearchResult
        {
            get
            {
                return this.DoctorSearchResultField;
            }
            set
            {
                this.DoctorSearchResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ECCVisitMode
        {
            get
            {
                return this.ECCVisitModeField;
            }
            set
            {
                this.ECCVisitModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMRReferralIn
        {
            get
            {
                return this.EMRReferralInField;
            }
            set
            {
                this.EMRReferralInField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityCode
        {
            get
            {
                return this.EntityCodeField;
            }
            set
            {
                this.EntityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FallRisk
        {
            get
            {
                return this.FallRiskField;
            }
            set
            {
                this.FallRiskField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HealthPlanCode
        {
            get
            {
                return this.HealthPlanCodeField;
            }
            set
            {
                this.HealthPlanCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LabOrdered
        {
            get
            {
                return this.LabOrderedField;
            }
            set
            {
                this.LabOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MedOrdered
        {
            get
            {
                return this.MedOrderedField;
            }
            set
            {
                this.MedOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NoConsultation
        {
            get
            {
                return this.NoConsultationField;
            }
            set
            {
                this.NoConsultationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.PatientLiteSearchResult PatientLiteSearchResult
        {
            get
            {
                return this.PatientLiteSearchResultField;
            }
            set
            {
                this.PatientLiteSearchResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ProcedureOrdered
        {
            get
            {
                return this.ProcedureOrderedField;
            }
            set
            {
                this.ProcedureOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RadOrdered
        {
            get
            {
                return this.RadOrderedField;
            }
            set
            {
                this.RadOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDateTime
        {
            get
            {
                return this.RegistrationDateTimeField;
            }
            set
            {
                this.RegistrationDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceTypeCode
        {
            get
            {
                return this.ServiceTypeCodeField;
            }
            set
            {
                this.ServiceTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceTypeDescription
        {
            get
            {
                return this.ServiceTypeDescriptionField;
            }
            set
            {
                this.ServiceTypeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VaccineInjectionOrdered
        {
            get
            {
                return this.VaccineInjectionOrderedField;
            }
            set
            {
                this.VaccineInjectionOrderedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitActiveStatus
        {
            get
            {
                return this.VisitActiveStatusField;
            }
            set
            {
                this.VisitActiveStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitNumber
        {
            get
            {
                return this.VisitNumberField;
            }
            set
            {
                this.VisitNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitRemarks
        {
            get
            {
                return this.VisitRemarksField;
            }
            set
            {
                this.VisitRemarksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitTypeCode
        {
            get
            {
                return this.VisitTypeCodeField;
            }
            set
            {
                this.VisitTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisitTypeDescription
        {
            get
            {
                return this.VisitTypeDescriptionField;
            }
            set
            {
                this.VisitTypeDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoctorSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class DoctorSearchResult : object
    {
        
        private string DoctorDomainIdField;
        
        private string DoctorMCRField;
        
        private string DoctorNameField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorDomainId
        {
            get
            {
                return this.DoctorDomainIdField;
            }
            set
            {
                this.DoctorDomainIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorMCR
        {
            get
            {
                return this.DoctorMCRField;
            }
            set
            {
                this.DoctorMCRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoctorName
        {
            get
            {
                return this.DoctorNameField;
            }
            set
            {
                this.DoctorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClinicLiteSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class ClinicLiteSearchResult : object
    {
        
        private string ClinicCodeField;
        
        private string ClinicNameField;
        
        private string EntityCodeField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClinicCode
        {
            get
            {
                return this.ClinicCodeField;
            }
            set
            {
                this.ClinicCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClinicName
        {
            get
            {
                return this.ClinicNameField;
            }
            set
            {
                this.ClinicNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityCode
        {
            get
            {
                return this.EntityCodeField;
            }
            set
            {
                this.EntityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IATrackingParameterDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class IATrackingParameterDTO : object
    {
        
        private RCMS.IATrackingSearchParameter SearchParameterField;
        
        private string SystemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.IATrackingSearchParameter SearchParameter
        {
            get
            {
                return this.SearchParameterField;
            }
            set
            {
                this.SearchParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemId
        {
            get
            {
                return this.SystemIdField;
            }
            set
            {
                this.SystemIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IATrackingSearchParameter", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class IATrackingSearchParameter : object
    {
        
        private string PatientSystemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientSystemId
        {
            get
            {
                return this.PatientSystemIdField;
            }
            set
            {
                this.PatientSystemIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IATrackingReturnDTO", Namespace="http://schemas.datacontract.org/2004/07/RCMS.DTOs.Integration.WebService")]
    public partial class IATrackingReturnDTO : object
    {
        
        private RCMS.ReturnDTO ReturnStatusField;
        
        private RCMS.IATrackingSearchResult[] SearchResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.ReturnDTO ReturnStatus
        {
            get
            {
                return this.ReturnStatusField;
            }
            set
            {
                this.ReturnStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.IATrackingSearchResult[] SearchResult
        {
            get
            {
                return this.SearchResultField;
            }
            set
            {
                this.SearchResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IATrackingSearchResult", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class IATrackingSearchResult : object
    {
        
        private RCMS.IATrackingList[] IATrackingListsField;
        
        private string PatientSystemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RCMS.IATrackingList[] IATrackingLists
        {
            get
            {
                return this.IATrackingListsField;
            }
            set
            {
                this.IATrackingListsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatientSystemId
        {
            get
            {
                return this.PatientSystemIdField;
            }
            set
            {
                this.PatientSystemIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IATrackingList", Namespace="http://schemas.datacontract.org/2004/07/RCMS.Search.Entities.Integration.WebServi" +
        "ce")]
    public partial class IATrackingList : object
    {
        
        private string DiagnosisCodeField;
        
        private string DiagnosisDescriptionField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        private string ServiceTypeCodeField;
        
        private string ServiceTypeDescriptionField;
        
        private System.Nullable<System.DateTime> StartDateField;
        
        private string System_IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnosisCode
        {
            get
            {
                return this.DiagnosisCodeField;
            }
            set
            {
                this.DiagnosisCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiagnosisDescription
        {
            get
            {
                return this.DiagnosisDescriptionField;
            }
            set
            {
                this.DiagnosisDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceTypeCode
        {
            get
            {
                return this.ServiceTypeCodeField;
            }
            set
            {
                this.ServiceTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceTypeDescription
        {
            get
            {
                return this.ServiceTypeDescriptionField;
            }
            set
            {
                this.ServiceTypeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate
        {
            get
            {
                return this.StartDateField;
            }
            set
            {
                this.StartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string System_ID
        {
            get
            {
                return this.System_IDField;
            }
            set
            {
                this.System_IDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RCMS.IPatientService")]
    public interface IPatientService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetPatientLite", ReplyAction="http://tempuri.org/IPatientService/GetPatientLiteResponse")]
        System.Threading.Tasks.Task<RCMS.GetPatientLiteResponse> GetPatientLiteAsync(RCMS.GetPatientLiteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetPatientInfo", ReplyAction="http://tempuri.org/IPatientService/GetPatientInfoResponse")]
        System.Threading.Tasks.Task<RCMS.GetPatientInfoResponse> GetPatientInfoAsync(RCMS.GetPatientInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetPatientQueue", ReplyAction="http://tempuri.org/IPatientService/GetPatientQueueResponse")]
        System.Threading.Tasks.Task<RCMS.GetPatientQueueResponse> GetPatientQueueAsync(RCMS.GetPatientQueueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientService/GetIATracking", ReplyAction="http://tempuri.org/IPatientService/GetIATrackingResponse")]
        System.Threading.Tasks.Task<RCMS.GetIATrackingResponse> GetIATrackingAsync(RCMS.GetIATrackingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientLite", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientLiteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.PatientLiteParameterDTO param;
        
        public GetPatientLiteRequest()
        {
        }
        
        public GetPatientLiteRequest(RCMS.PatientLiteParameterDTO param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientLiteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientLiteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.PatientLiteReturnDTO GetPatientLiteResult;
        
        public GetPatientLiteResponse()
        {
        }
        
        public GetPatientLiteResponse(RCMS.PatientLiteReturnDTO GetPatientLiteResult)
        {
            this.GetPatientLiteResult = GetPatientLiteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.PatientInfoParameterDTO param;
        
        public GetPatientInfoRequest()
        {
        }
        
        public GetPatientInfoRequest(RCMS.PatientInfoParameterDTO param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.PatientInfoReturnDTO GetPatientInfoResult;
        
        public GetPatientInfoResponse()
        {
        }
        
        public GetPatientInfoResponse(RCMS.PatientInfoReturnDTO GetPatientInfoResult)
        {
            this.GetPatientInfoResult = GetPatientInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientQueue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientQueueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.PatientQueueParameterDTO param;
        
        public GetPatientQueueRequest()
        {
        }
        
        public GetPatientQueueRequest(RCMS.PatientQueueParameterDTO param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientQueueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientQueueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.PatientQueueReturnDTO GetPatientQueueResult;
        
        public GetPatientQueueResponse()
        {
        }
        
        public GetPatientQueueResponse(RCMS.PatientQueueReturnDTO GetPatientQueueResult)
        {
            this.GetPatientQueueResult = GetPatientQueueResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIATracking", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetIATrackingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.IATrackingParameterDTO param;
        
        public GetIATrackingRequest()
        {
        }
        
        public GetIATrackingRequest(RCMS.IATrackingParameterDTO param)
        {
            this.param = param;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIATrackingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetIATrackingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RCMS.IATrackingReturnDTO GetIATrackingResult;
        
        public GetIATrackingResponse()
        {
        }
        
        public GetIATrackingResponse(RCMS.IATrackingReturnDTO GetIATrackingResult)
        {
            this.GetIATrackingResult = GetIATrackingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IPatientServiceChannel : RCMS.IPatientService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PatientServiceClient : System.ServiceModel.ClientBase<RCMS.IPatientService>, RCMS.IPatientService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PatientServiceClient() : 
                base(PatientServiceClient.GetDefaultBinding(), PatientServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPatientService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PatientServiceClient.GetBindingForEndpoint(endpointConfiguration), PatientServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PatientServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PatientServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<RCMS.GetPatientLiteResponse> GetPatientLiteAsync(RCMS.GetPatientLiteRequest request)
        {
            return base.Channel.GetPatientLiteAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCMS.GetPatientInfoResponse> GetPatientInfoAsync(RCMS.GetPatientInfoRequest request)
        {
            return base.Channel.GetPatientInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCMS.GetPatientQueueResponse> GetPatientQueueAsync(RCMS.GetPatientQueueRequest request)
        {
            return base.Channel.GetPatientQueueAsync(request);
        }
        
        public System.Threading.Tasks.Task<RCMS.GetIATrackingResponse> GetIATrackingAsync(RCMS.GetIATrackingRequest request)
        {
            return base.Channel.GetIATrackingAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPatientService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPatientService))
            {
                return new System.ServiceModel.EndpointAddress("https://sgsrcmsut6dr:9001/PatientService.svc/PatientService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PatientServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPatientService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PatientServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPatientService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPatientService,
        }
    }
}
