//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Win.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MessageQueueAttachment
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int MessageQueueAttachmentNo { get; set; }
        public Nullable<int> MessageQueueNo { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentURL { get; set; }
        public Nullable<bool> IsEmbed { get; set; }
        public Nullable<int> VenueNo { get; set; }
        public Nullable<int> VenueBranchNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
