//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Win.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReportMaster
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ReportNo { get; set; }
        public string ReportKey { get; set; }
        public string ReportName { get; set; }
        public string Description { get; set; }
        public string ProcedureName { get; set; }
        public string ReportPath { get; set; }
        public string ExportPath { get; set; }
        public string ExportURL { get; set; }
        public string Parameterstring { get; set; }
        public Nullable<int> VenueNo { get; set; }
        public Nullable<int> VenueBranchNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> UnDeletedFileDays { get; set; }
    }
}
