//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Win.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int UserNo { get; set; }
        public string UserName { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public bool Status { get; set; }
        public int VenueNo { get; set; }
        public int VenueBranchNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsRider { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
        public Nullable<bool> IsMarketing { get; set; }
        public Nullable<bool> PatientInfoEdit { get; set; }
        public Nullable<bool> DueReportPrint { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public Nullable<bool> IsApproval { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> Discount { get; set; }
        public string otp { get; set; }
        public Nullable<System.DateTime> otpexpiry { get; set; }
        public string Specialisation { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> UDOB { get; set; }
        public Nullable<System.DateTime> UDOJ { get; set; }
        public Nullable<System.DateTime> UDOR { get; set; }
        public Nullable<bool> IsProvisional { get; set; }
        public string DefaultPage { get; set; }
        public string Qualification { get; set; }
        public Nullable<bool> SuppressSCDtTm { get; set; }
        public Nullable<bool> IsPathologist { get; set; }
        public Nullable<bool> IsResultEntryHIV { get; set; }
        public Nullable<bool> IsEditLabResults { get; set; }
        public Nullable<bool> IsResultEntryVIP { get; set; }
        public Nullable<bool> isDiscountApproval { get; set; }
        public Nullable<bool> Isdue { get; set; }
    }
}
