//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Win.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CSATransaction
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int CSATransactionNo { get; set; }
        public int CustomerNo { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int SampleCount { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public Nullable<int> VenueNo { get; set; }
        public Nullable<int> VenueBranchNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CollectedStatus { get; set; }
    }
}
