//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Win.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MessageCommunication
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int CommuncationNo { get; set; }
        public string Host { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> IsSSL { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string CommunicationType { get; set; }
        public Nullable<int> VenueNo { get; set; }
        public Nullable<int> VenueBranchNo { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Param3 { get; set; }
    }
}
