//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Win.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ScheduleReport
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int ScheduleReportNo { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime Todate { get; set; }
        public bool IsHeader { get; set; }
        public int IsGenerate { get; set; }
        public bool Status { get; set; }
        public int VenueNo { get; set; }
        public int VenueBranchNo { get; set; }
    }
}
