//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAP
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientRequest", Namespace="http://schemas.datacontract.org/2004/07/PatientInfoSVC")]
    public partial class PatientRequest : object
    {
        
        private string EinriField;
        
        private string DocNumField;
        
        private string PatnrField;
        
        private string FalnrField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Einri
        {
            get
            {
                return this.EinriField;
            }
            set
            {
                this.EinriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DocNum
        {
            get
            {
                return this.DocNumField;
            }
            set
            {
                this.DocNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Patnr
        {
            get
            {
                return this.PatnrField;
            }
            set
            {
                this.PatnrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Falnr
        {
            get
            {
                return this.FalnrField;
            }
            set
            {
                this.FalnrField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientResponse", Namespace="http://schemas.datacontract.org/2004/07/PatientInfoSVC")]
    public partial class PatientResponse : object
    {
        
        private string DocNumField;
        
        private string FalnrField;
        
        private string PatnrField;
        
        private string NameFirstField;
        
        private string NameLastField;
        
        private string SexidField;
        
        private string BirthdtField;
        
        private string AltidtypeField;
        
        private string PntExtnrField;
        
        private string RaceField;
        
        private string RacedescField;
        
        private string BuNatioField;
        
        private string NatiodescField;
        
        private string VipIndField;
        
        private string OrgpfField;
        
        private string ZimmrField;
        
        private string BettField;
        
        private string AllergyIndField;
        
        private string AllergenField;
        
        private string AdPstcd1Field;
        
        private string AdBldngField;
        
        private string AdFloorField;
        
        private string AdRoomnumField;
        
        private string AdStreetField;
        
        private string BuildingField;
        
        private string Land1Field;
        
        private string AdMonmbrField;
        
        private string OffnmbrField;
        
        private string AdTlnmbrField;
        
        private string EmailField;
        
        private string PatOccuField;
        
        private string RetMsgField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocNum
        {
            get
            {
                return this.DocNumField;
            }
            set
            {
                this.DocNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Falnr
        {
            get
            {
                return this.FalnrField;
            }
            set
            {
                this.FalnrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patnr
        {
            get
            {
                return this.PatnrField;
            }
            set
            {
                this.PatnrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string NameFirst
        {
            get
            {
                return this.NameFirstField;
            }
            set
            {
                this.NameFirstField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string NameLast
        {
            get
            {
                return this.NameLastField;
            }
            set
            {
                this.NameLastField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sexid
        {
            get
            {
                return this.SexidField;
            }
            set
            {
                this.SexidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Birthdt
        {
            get
            {
                return this.BirthdtField;
            }
            set
            {
                this.BirthdtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Altidtype
        {
            get
            {
                return this.AltidtypeField;
            }
            set
            {
                this.AltidtypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string PntExtnr
        {
            get
            {
                return this.PntExtnrField;
            }
            set
            {
                this.PntExtnrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Race
        {
            get
            {
                return this.RaceField;
            }
            set
            {
                this.RaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Racedesc
        {
            get
            {
                return this.RacedescField;
            }
            set
            {
                this.RacedescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string BuNatio
        {
            get
            {
                return this.BuNatioField;
            }
            set
            {
                this.BuNatioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Natiodesc
        {
            get
            {
                return this.NatiodescField;
            }
            set
            {
                this.NatiodescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string VipInd
        {
            get
            {
                return this.VipIndField;
            }
            set
            {
                this.VipIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string Orgpf
        {
            get
            {
                return this.OrgpfField;
            }
            set
            {
                this.OrgpfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string Zimmr
        {
            get
            {
                return this.ZimmrField;
            }
            set
            {
                this.ZimmrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string Bett
        {
            get
            {
                return this.BettField;
            }
            set
            {
                this.BettField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string AllergyInd
        {
            get
            {
                return this.AllergyIndField;
            }
            set
            {
                this.AllergyIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Allergen
        {
            get
            {
                return this.AllergenField;
            }
            set
            {
                this.AllergenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string AdPstcd1
        {
            get
            {
                return this.AdPstcd1Field;
            }
            set
            {
                this.AdPstcd1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string AdBldng
        {
            get
            {
                return this.AdBldngField;
            }
            set
            {
                this.AdBldngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string AdFloor
        {
            get
            {
                return this.AdFloorField;
            }
            set
            {
                this.AdFloorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string AdRoomnum
        {
            get
            {
                return this.AdRoomnumField;
            }
            set
            {
                this.AdRoomnumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public string AdStreet
        {
            get
            {
                return this.AdStreetField;
            }
            set
            {
                this.AdStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string Building
        {
            get
            {
                return this.BuildingField;
            }
            set
            {
                this.BuildingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string Land1
        {
            get
            {
                return this.Land1Field;
            }
            set
            {
                this.Land1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string AdMonmbr
        {
            get
            {
                return this.AdMonmbrField;
            }
            set
            {
                this.AdMonmbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string Offnmbr
        {
            get
            {
                return this.OffnmbrField;
            }
            set
            {
                this.OffnmbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=28)]
        public string AdTlnmbr
        {
            get
            {
                return this.AdTlnmbrField;
            }
            set
            {
                this.AdTlnmbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=29)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=30)]
        public string PatOccu
        {
            get
            {
                return this.PatOccuField;
            }
            set
            {
                this.PatOccuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=31)]
        public string RetMsg
        {
            get
            {
                return this.RetMsgField;
            }
            set
            {
                this.RetMsgField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAP.IPatientInfo")]
    public interface IPatientInfo
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPatientInfo/GetPatientInfo", ReplyAction="http://tempuri.org/IPatientInfo/GetPatientInfoResponse")]
        System.Threading.Tasks.Task<SAP.GetPatientInfoResponse> GetPatientInfoAsync(SAP.GetPatientInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SAP.PatientRequest request;
        
        public GetPatientInfoRequest()
        {
        }
        
        public GetPatientInfoRequest(SAP.PatientRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPatientInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPatientInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SAP.PatientResponse GetPatientInfoResult;
        
        public GetPatientInfoResponse()
        {
        }
        
        public GetPatientInfoResponse(SAP.PatientResponse GetPatientInfoResult)
        {
            this.GetPatientInfoResult = GetPatientInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IPatientInfoChannel : SAP.IPatientInfo, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PatientInfoClient : System.ServiceModel.ClientBase<SAP.IPatientInfo>, SAP.IPatientInfo
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PatientInfoClient() : 
                base(PatientInfoClient.GetDefaultBinding(), PatientInfoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.sapBioSVC.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientInfoClient(EndpointConfiguration endpointConfiguration) : 
                base(PatientInfoClient.GetBindingForEndpoint(endpointConfiguration), PatientInfoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientInfoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PatientInfoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientInfoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PatientInfoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PatientInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SAP.GetPatientInfoResponse> GetPatientInfoAsync(SAP.GetPatientInfoRequest request)
        {
            return base.Channel.GetPatientInfoAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.sapBioSVC))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.sapBioSVC))
            {
                return new System.ServiceModel.EndpointAddress("https://sguwebwb7rh:9008/PatientInfo.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PatientInfoClient.GetBindingForEndpoint(EndpointConfiguration.sapBioSVC);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PatientInfoClient.GetEndpointAddress(EndpointConfiguration.sapBioSVC);
        }
        
        public enum EndpointConfiguration
        {
            
            sapBioSVC,
        }
    }
}
